export const SPLASH_SCREEN = 'SPLASH_SCREEN'
export const SIGNIN_SCREEN = 'SIGNIN_SCREEN'
export const OTP_SCREEN = 'OTP_SCREEN'
export const HOME_SCREEN = 'HOME_SCREEN'
export const COMPLAINTS_SCREEN = 'COMPLAINTS_SCREEN'
export const APPLICATIONS_SCREEN = 'APPLICATIONS_SCREEN'
export const GALLERY_SCREEN = 'GALLERY_SCREEN'
export const CONTACT_US_SCREEN = 'CONTACT_US_SCREEN'



export const HOME_DRAWER = 'HOME_DRAWER'
export const BOTTOM_TABS = 'BOTTOM_TABS'
export const HOME_STACK = 'HOME_STACK'
export const COMPLAINTS_STACK = 'COMPLAINTS_STACK'
export const APPLICATIONS_STACK = 'APPLICATIONS_STACK'
export const GALLERY_STACK = 'GALLERY_STACK'
export const CONTACT_US_STACK = 'CONTACT_US_STACK'